"""add index for embeddings

Revision ID: 16e380cc05a7
Revises: 79e67597a081
Create Date: 2025-08-14 19:15:44.206466

"""
from typing import Sequence, Union

import sqlalchemy as sa

from pgvector.sqlalchemy import Vector

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '16e380cc05a7'
down_revision: Union[str, None] = '79e67597a081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET LOCAL maintenance_work_mem = '128MB';")
    op.create_index(
        'ix_embeddings_vector_ivfflat_cosine',
        'embeddings',
        ['vector'],
        unique=False,
        postgresql_using='ivfflat',
        postgresql_ops={'vector': 'vector_cosine_ops'},
        postgresql_with={'lists': 100}  # restore to original value for performance
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET LOCAL maintenance_work_mem = '128MB';")
    op.drop_index(
        'ix_embeddings_vector_ivfflat_cosine',
        table_name='embeddings',
        postgresql_using='ivfflat',
        postgresql_ops={'vector': 'vector_cosine_ops'},
        postgresql_with={'lists': 100}  # match the value in upgrade
    )
    # ### end Alembic commands ###
