"""updating_overall_structure

Revision ID: 1ef3915e7c9a
Revises: cb13bcddc8d0
Create Date: 2025-07-15 13:27:03.146841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ef3915e7c9a'
down_revision: Union[str, None] = 'cb13bcddc8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_items',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('sectionable_type', sa.String(), nullable=False),
    sa.Column('sectionable_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('images')
    op.drop_table('sectionables')
    op.drop_column('documents', 'contentable_id')
    op.drop_column('documents', 'contentable_type')
    op.add_column('listing_items', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('listing_items', sa.Column('listable_type', sa.String(), nullable=False))
    op.add_column('listing_items', sa.Column('listable_id', sa.Integer(), nullable=False))
    op.drop_column('listing_items', 'listing_item_id')
    op.add_column('listings', sa.Column('section_item_id', sa.Integer(), nullable=False))
    op.drop_column('tables', 'section_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('section_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('listings', 'section_item_id')
    op.add_column('listing_items', sa.Column('listing_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('listing_items', 'listable_id')
    op.drop_column('listing_items', 'listable_type')
    op.drop_column('listing_items', 'position')
    op.add_column('documents', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('sectionables',
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sectionable_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sectionable_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sectionables_pkey'))
    )
    op.create_table('images',
    sa.Column('section_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('images_pkey'))
    )
    op.drop_table('section_items')
    # ### end Alembic commands ###
