"""fix_for_nullable

Revision ID: 21d253652beb
Revises: fc72dba4a6d7
Create Date: 2025-07-29 13:12:58.732568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '21d253652beb'
down_revision: Union[str, None] = 'fc72dba4a6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('element', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Document that this element is a part of')
    op.create_unique_constraint('uq_element_type_document_id', 'element', ['type', 'document_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_element_type_document_id', 'element', type_='unique')
    op.alter_column('element', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Document that this element is a part of')
    # ### end Alembic commands ###
