"""update chunk columns

Revision ID: 6b0771e91725
Revises: fd073c241c1f
Create Date: 2025-08-06 12:54:11.481232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '6b0771e91725'
down_revision: Union[str, None] = 'fd073c241c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('token_model', sa.String(), nullable=False))
    op.add_column('chunks', sa.Column('token_count', sa.Integer(), nullable=False))
    op.drop_column('chunks', 'tokens_count')
    op.drop_column('chunks', 'tokens')
    op.drop_column('chunks', 'chunk_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('tokens', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('tokens_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('chunks', 'token_count')
    op.drop_column('chunks', 'token_model')
    # ### end Alembic commands ###
