"""update chunk indexing

Revision ID: 89cfe75a5fd8
Revises: 6b0771e91725
Create Date: 2025-08-10 13:27:40.979343

"""
from typing import Sequence, Union

import sqlalchemy as sa

from pgvector.sqlalchemy import Vector

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '89cfe75a5fd8'
down_revision: Union[str, None] = '6b0771e91725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Increase maintenance_work_mem for this session to allow large index creation
    op.execute("SET LOCAL maintenance_work_mem = '128MB';")
    op.create_index('ix_chunks_embedding_ivfflat_cosine', 'chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_embedding_ivfflat_cosine', table_name='chunks', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    # ### end Alembic commands ###
