"""update tree indexing

Revision ID: b0957e0b777f
Revises: 9ca0d03039cb
Create Date: 2025-08-03 14:11:27.822358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'b0957e0b777f'
down_revision: Union[str, None] = '9ca0d03039cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_element_type_document_id'), 'elements', type_='unique')
    op.create_index('idx_elements_document_id_type', 'elements', ['document_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_elements_document_id_type', table_name='elements')
    op.create_unique_constraint(op.f('uq_element_type_document_id'), 'elements', ['type', 'document_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
