"""Add ForeignKey to answers.question_id

Revision ID: c1f6d67790b6
Revises: 1ef3915e7c9a
Create Date: 2025-07-19 20:34:29.965431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1f6d67790b6'
down_revision: Union[str, None] = '1ef3915e7c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('start_urls', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_domains', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'READY', 'RUNNING', 'PAUSED', 'FAILED', 'CANCELLED', 'SUCCEEDED', 'MEANINGS', 'TRANSITIONS', name='crawl_job_status'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crawl_job_id', sa.Integer(), nullable=False),
    sa.Column('crawl_item_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_items',
    sa.Column('crawl_job_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response_headers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('referer', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_table('crawl_items')
    op.drop_table('crawl_log')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
