"""convert_log_level_from_enum_to_string

Revision ID: e0cb8e52608b
Revises: 20efbb295cb3
Create Date: 2025-07-22 16:49:11.955301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0cb8e52608b'
down_revision: Union[str, None] = '20efbb295cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_logs', 'level',
               existing_type=postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_logs', 'level',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'),
               existing_nullable=False)
    # ### end Alembic commands ###
