"""updating_contentable

Revision ID: e25b67b8eb4b
Revises: 83a900f9a687
Create Date: 2025-07-29 00:02:58.786677

"""
from typing import Sequence, Union

import sqlalchemy as sa

from pgvector.sqlalchemy import Vector

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e25b67b8eb4b'
down_revision: Union[str, None] = '83a900f9a687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_blocks', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('code_blocks', 'sectionable_type')
    op.drop_column('code_blocks', 'section_item_id')
    op.drop_column('code_blocks', 'contentable_type')
    op.drop_column('code_blocks', 'contentable_id')
    op.drop_column('code_blocks', 'sectionable_id')
    op.add_column('documents', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('documents', 'contentable_type')
    op.drop_column('documents', 'contentable_id')
    op.add_column('listing_items', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('listing_items', 'contentable_type')
    op.drop_column('listing_items', 'contentable_id')
    op.add_column('listings', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_constraint(op.f('listings_section_item_id_fkey'), 'listings', type_='foreignkey')
    op.drop_column('listings', 'sectionable_type')
    op.drop_column('listings', 'section_item_id')
    op.drop_column('listings', 'listable_type')
    op.drop_column('listings', 'listable_id')
    op.drop_column('listings', 'contentable_type')
    op.drop_column('listings', 'contentable_id')
    op.drop_column('listings', 'sectionable_id')
    op.add_column('paragraphs', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_constraint(op.f('paragraphs_section_item_id_fkey'), 'paragraphs', type_='foreignkey')
    op.drop_column('paragraphs', 'sectionable_type')
    op.drop_column('paragraphs', 'section_item_id')
    op.drop_column('paragraphs', 'listable_type')
    op.drop_column('paragraphs', 'listable_id')
    op.drop_column('paragraphs', 'contentable_type')
    op.drop_column('paragraphs', 'contentable_id')
    op.drop_column('paragraphs', 'sectionable_id')
    op.add_column('sections', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('sections', 'contentable_type')
    op.drop_column('sections', 'contentable_id')
    op.add_column('sentences', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('sentences', 'contentable_type')
    op.drop_column('sentences', 'contentable_id')
    op.add_column('table_row_cells', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('table_row_cells', 'contentable_type')
    op.drop_column('table_row_cells', 'contentable_id')
    op.add_column('table_rows', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('table_rows', 'contentable_type')
    op.drop_column('table_rows', 'contentable_id')
    op.add_column('tables', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('tables', 'sectionable_type')
    op.drop_column('tables', 'listable_type')
    op.drop_column('tables', 'listable_id')
    op.drop_column('tables', 'contentable_type')
    op.drop_column('tables', 'contentable_id')
    op.drop_column('tables', 'sectionable_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('sectionable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tables', sa.Column('listable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('listable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tables', sa.Column('sectionable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tables', 'content')
    op.add_column('table_rows', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('table_rows', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('table_rows', 'content')
    op.add_column('table_row_cells', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('table_row_cells', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('table_row_cells', 'content')
    op.add_column('sentences', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sentences', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sentences', 'content')
    op.add_column('sections', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sections', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sections', 'content')
    op.add_column('paragraphs', sa.Column('sectionable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paragraphs', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paragraphs', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('paragraphs', sa.Column('listable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paragraphs', sa.Column('listable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('paragraphs', sa.Column('section_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('paragraphs', sa.Column('sectionable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('paragraphs_section_item_id_fkey'), 'paragraphs', 'section_items', ['section_item_id'], ['id'])
    op.drop_column('paragraphs', 'content')
    op.add_column('listings', sa.Column('sectionable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('listable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('listable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('section_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('sectionable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('listings_section_item_id_fkey'), 'listings', 'section_items', ['section_item_id'], ['id'])
    op.drop_column('listings', 'content')
    op.add_column('listing_items', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('listing_items', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('listing_items', 'content')
    op.add_column('documents', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'content')
    op.drop_column('crawl_logs', 'level')
    op.drop_column('crawl_jobs', 'status')
    op.add_column('code_blocks', sa.Column('sectionable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('code_blocks', sa.Column('contentable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('code_blocks', sa.Column('contentable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('code_blocks', sa.Column('section_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('code_blocks', sa.Column('sectionable_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('code_blocks', 'content')
    # ### end Alembic commands ###
