"""convert_log_level_from_enum_to_string

Revision ID: ecabc0b5bdb0
Revises: e0cb8e52608b
Create Date: 2025-07-22 21:57:48.857343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ecabc0b5bdb0'
down_revision: Union[str, None] = 'e0cb8e52608b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
